name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Version
        run: |
          echo "MOVIEPILOT_VERSION=$(jq -r '.moviepilot_version' version.json)" >> $GITHUB_ENV
          echo "P115STRMHELPER_VERSION=$(jq -r '.p115strmhelper_version' version.json)" >> $GITHUB_ENV

      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/moviepilot-oof
          tags: |
            type=raw,value=${{ env.MOVIEPILOT_VERSION }}_${{ env.P115STRMHELPER_VERSION }}
            type=raw,value=latest

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          build-args: |
            MOVIEPILOT_VERSION=${{ env.MOVIEPILOT_VERSION }}
            P115STRMHELPER_VERSION=${{ env.P115STRMHELPER_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
